USE master;

IF DB_ID('RestWithAspDotNetDB') IS NOT NULL
BEGIN
    ALTER DATABASE RestWithAspDotNetDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE RestWithAspDotNetDB;
END

RESTORE DATABASE RestWithAspDotNetDB
FROM DISK = '/docker-entrypoint-initdb.d/RestWithAspDotNetDB.bak'
WITH REPLACE, RECOVERY;
