// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestWithAsp.Net.Data;

#nullable disable

namespace RestWithAsp.Net.Migrations
{
    [DbContext(typeof(RestWithAspDotNetContext))]
    [Migration("20231224105406_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestWithAsp.Net.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Michael C. Feathers",
                            LaunchDate = new DateTime(2017, 11, 29, 13, 50, 5, 878, DateTimeKind.Unspecified),
                            Price = 49.00m,
                            Title = "Working effectively with legacy code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ralph Johnson, Erich Gamma, John Vlissides e Richard Helm",
                            LaunchDate = new DateTime(2017, 11, 29, 15, 15, 13, 636, DateTimeKind.Unspecified),
                            Price = 77.00m,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert C. Martin",
                            LaunchDate = new DateTime(2009, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 67.00m,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Crockford",
                            LaunchDate = new DateTime(2017, 11, 7, 15, 9, 1, 674, DateTimeKind.Unspecified),
                            Price = 67.00m,
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Steve McConnell",
                            LaunchDate = new DateTime(2017, 11, 7, 15, 9, 1, 674, DateTimeKind.Unspecified),
                            Price = 58.00m,
                            Title = "Refactoring"
                        });
                });

            modelBuilder.Entity("RestWithAsp.Net.Model.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "São Paulo - Brasil",
                            FirstName = "Ayrton",
                            Gender = "Male",
                            LastName = "Senna"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Anchiano - Italy",
                            FirstName = "Leonardo",
                            Gender = "Male",
                            LastName = "da Vinci"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Porbandar - India",
                            FirstName = "Mahatma",
                            Gender = "Male",
                            LastName = "Gandhi"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Kentuky - USA",
                            FirstName = "Mohamed",
                            Gender = "Male",
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = 5L,
                            Address = "Mvezo - South Africa",
                            FirstName = "Nelson",
                            Gender = "Male",
                            LastName = "Mandela"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
